# Generated by Django 3.0.5 on 2022-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_name', models.CharField(max_length=500)),
                ('video_frames_name', models.CharField(max_length=500)),
                ('video_cropped_name', models.CharField(max_length=500)),
            ],
        ),
    ]
